name: habit_heat
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  percent_indicator: ^4.0.0
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  google_sign_in: ^5.2.3
  flutter_signin_button: ^2.0.0
  firebase_auth: ^3.3.6
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  url_launcher: ^6.0.20  
  flutter_heatmap_calendar: ^1.0.3
  month_picker_dialog: ^0.4.0
<<<<<<< Updated upstream
  lottie: ^1.2.2
  http: ^0.13.4
  geolocator: ^8.2.0
  shimmer:
=======
  expandable: ^5.0.1
>>>>>>> Stashed changes

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - images/
    - assets/icons/
    - assets/lottie/

  uses-material-design: true

